### ISSUE TITLE
다음 모일 시간을 정해봅시다!

### ISSUE THREAD

**Issue by Taehan2** [SukJune/Comnet-team6#2]

**Comment by haebeompark** [comment]
전 화요일은 안되고 수요일은 언제든 되요 목, 금은 오후가능 주말도 가능

**Comment by juwonha** [comment]
전 이번주는 토요일은 안되고 수,금은 오후6시 이후부터 목은 4시 이후부터 될것같고 일요일은 언제든 가능해요

**Comment by Taehan2** [comment]
음....종합해보면 금요일 저녁이나 일요일이 좋을거같은데!
석준이형 가능하면 금요일저녁이나 일요일로하자 어때?!

**Comment by haebeompark** [comment]
그럼 일요일 2시쯤에 괜찮을까요

**Comment by SukJune** [comment]
일요일 2시 좋다!!
